version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    container_name: hnired-test-e2e
    build:
      context: .
      target: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: hnhired-test
